#!/bin/sh
pip3 install -r requirements.txt
mkdir -p /etc/thlogger
mkdir -p /var/log/thlogger
cp thlogger.py /etc/thlogger/
cp thlogger.conf /etc/thlogger/
cp thlogger.service /lib/systemd/system/
chmod 644 /lib/systemd/system/thlogger.service
systemctl daemon-reload
systemctl enable thlogger.service --now
