#!/bin/sh
mkdir -p /etc/thlogger
mkdir -p /var/log/thlogger
mkdir -p /opt/thlogger
python3 -m venv /opt/thlogger/venv
/opt/thlogger/venv/bin/pip install -r requirements.txt
cp thlogger.py /etc/thlogger/
cp thlogger.conf /etc/thlogger/
cp thlogger.service /lib/systemd/system/
touch /var/log/thlogger/thlogger.log
chmod 644 /var/log/thlogger/thlogger.log
chmod 644 /lib/systemd/system/thlogger.service
systemctl daemon-reload
systemctl enable thlogger.service --now
