#!/bin/sh
mkdir /etc/thlogger
mkdir /var/log/thlogger
cp thlogger.py /etc/thlogger/
cp thlogger.conf /etc/thlogger/
cp thlogger.service /lib/systemd/system/
chmod 644 /lib/systemd/system/thlogger.service
systemctl daemon-reload
systemctl enable thlogger.service --now
