version: '3'

services:
    influxdb:
        restart: unless-stopped
        image: influxdb:2.1
        volumes:
            - ./vol_influxdb:/var/lib/influxdb2
        ports:
            - 8086:8086

    grafana:
        restart: unless-stopped
        image: grafana/grafana:master-ubuntu
        ports:
            - 8080:3000
