version: '3'

services:
    influxdb:
        restart: always
        image: influxdb
        volumes:
            - ./vol:/var/lib/influxdb
        ports:
            - 8086:8086
        env_file:
            - influxdb.env

    grafana:
        restart: always
        image: grafana/grafana
        ports:
            - 8080:3000
